[program:voicelink-ws]
command=/usr/bin/php /var/www/html/web-rtc/bin/websocket-server.php
directory=/var/www/html/web-rtc
user=www-data
autostart=true
autorestart=true
startretries=5
startsecs=3
redirect_stderr=true
stdout_logfile=/var/www/html/web-rtc/application/logs/websocket-supervisor.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=3
environment=HOME="/var/www"
